name: pytest

on: [push, pull_request]

jobs:
  pytest:
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      QT_QPA_PLATFORM: offscreen
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
        pyqt-version: ["6.7.1"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt install libgl1 libegl1 libglib2.0-0 libxcb-image0 libxkbcommon-x11-0 libxcb-icccm4 libxcb-keysyms1 xserver-xephyr libfontconfig1 libxkbcommon-dev libdbus-1-3 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0 libxcb-cursor0
          python -m pip install --upgrade pip
          pip install .
          # We want to test against installed package instead of source files
          pip install . --target beeref_inst
          rm -r beeref
          mv beeref_inst/beeref beeref
          rm -r beeref_inst
          pip install -r requirements/test.txt
      - name: Run Unittests with pytest
        run: pytest -x --cov --cov-report=xml
      - name: Upload Coverage report to Codecov
        if: env.CODECOV_TOKEN != ''
        uses: codecov/codecov-action@v4
        with:
          verbose: true
          fail_ci_if_error: true
          token: ${{ env.CODECOV_TOKEN }}
